pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                git url: 'https://github.com/Surya-pkh/Dev_OPS/tree/main/Jenkins/'
            }
        }
        stage('Run Script') {
            steps {
                sh 'chmod +x Sample.sh'
                sh './Sample.sh'
                sh 'cat output.txt'
            }
        }
    }

    post {
        always {
            emailext(
                subject: "Jenkins Job: ${env.JOB_NAME} #${env.BUILD_NUMBER} - ${currentBuild.currentResult}",
                body: """<p>Build Output:</p>
<pre>${env.BUILD_URL}console</pre>""",
                to: 'gcpsurya27@gmail.com'
            )
        }
    }
}
