pipeline {
    agent any
    environment {
        RECIPIENT = 'gcpsurya27@gmail.com'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Run Script') {
            steps {
                sh 'bash Jenkins/Simple-Pipeline/Sample.sh'
            }
        }
    }
    post {
    success {
        emailext(
            subject: "✅ Build Success - ${env.JOB_NAME} #${env.BUILD_NUMBER}",
            body: "Build ${env.BUILD_NUMBER} succeeded.\n\nJob: ${env.JOB_NAME}\nURL: ${env.BUILD_URL}",
            to: "gcpsurya27@gmail.com",
            replyTo: "gcpsurya27@gmail.com",
            from: "gcpsurya27@gmail.com"
        )
    }
    failure {
        emailext(
            subject: "❌ Build Failed - ${env.JOB_NAME} #${env.BUILD_NUMBER}",
            body: "Build ${env.BUILD_NUMBER} failed.\n\nJob: ${env.JOB_NAME}\nURL: ${env.BUILD_URL}",
            to: "gcpsurya27@gmail.com",
            replyTo: "gcpsurya27@gmail.com",
            from: "gcpsurya27@gmail.com"
        )
    }
}

}
